services:

  shippingorderDB:
    container_name: shippingorderDB
    environment:       
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrongP@ssw0rd123
    restart: always
    ports:
      - "1402:1433" 
  
  shippingorder.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - shippingorderDB
