services:
  ErpDb:
    container_name: ErpDb
    environment:
      - ACCEPT_EULA='Y'
      - MSSQL_SA_PASSWORD=StrongP@ssw0rd123
      - MSSQL_TCP_PORT= 1433
    restart: always
    ports:
      - "11433:1433"
   
  messagebroker:
    container_name: MqMessageBroker
    hostname: erp-mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  shippingorder.api:
    container_name: shippingorderapi
    environment:
      - ConnectionStrings:Database=Server=ErpDb;Database=PurchasingOrderDb;User Id=sa;Password=StrongP@ssw0rd123;Encrypt=False;TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - MessageBroker:Host=amqp://erp-mq:5672
      - MessageBroker:UserName=guest
      - MessageBroker:Password=guest
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"

    ports:
      - "6100:8080"
      - "6160:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - ErpDb
      - messagebroker

  elasticsearch:
    container_name: elasticsearch
    ports:
    - 9200:9200
    environment:
    - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    - discovery.type=single-node
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -vq '\"status\":\"red\"'"]
      interval: 20s
      timeout: 5s
      retries: 5

  kibana:
    container_name: kibana
    ports:
    - 5601:5601
    depends_on:
        elasticsearch:
          condition: service_healthy
    environment:
    - ELASTICSEARCH_URL=http://localhost:9200
    - xpack.security.enabled= false

